travel/apps/trains/urls.py
from django.urls import path
from .views import (home, TrainCreateView, TrainDetailView, TrainUpdateView, TrainDeleteView)

app_name = "train"

urlpatterns = [
    path('', home, name='home'),
    path('detail/<int:pk>/', TrainDetailView.as_view(), name='detail'),
    path('add/', TrainCreateView.as_view(), name='add'),
    path('update/<int:pk>/', TrainUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', TrainDeleteView.as_view(), name='delete'),

]

travel/urls.py
from django.contrib import admin
from django.urls import path, include
from routes.views import (home, find_routes, add_route,
                          RouteListView, RouteDetailView, RouteDeleteView)
from .views import login_view, logout_view, register_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('', home, name="home"),
    path('list/', RouteListView.as_view(), name="list"),
    path('detail/<int:pk>/', RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', RouteDeleteView.as_view(), name='delete'),
    path('find/', find_routes, name="find_routes"),
    path('add_route/', add_route, name="add_route"),
    path('cities/', include('cities.urls')),
    path('trains/', include('trains.urls')),

]

travel/apps/trains/models.py
from django.db import models
from cities.models import City
from django.core.exceptions import ValidationError


class Train(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название поезда')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='Откуда', related_name='from_city')
    to_city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='Куда', related_name='to_city')
    travel_time = models.IntegerField(verbose_name=' Время пути')

    def __str__(self):
        return 'Поезд № {} из {} в {}'.format(self.name, self.from_city, self.to_city)

    class Meta:
        verbose_name = 'Поезд'
        verbose_name_plural = 'Поезда'
        ordering = ['name']

    def clean(self, *args, **kwargs):
        if self.from_city == self.to_city:
            raise ValidationError('Измените город прибытия ')
        qs = Train.objects.filter(from_city=self.from_city,
                                  to_city=self.to_city,
                                  travel_time=self.travel_time).exclude(pk=self.pk)
        if qs.exists():
            raise ValidationError('Измените время в пути')

        return super(Train, self).clean(*args, **kwargs)

travel/apps/trains/forms.py
from django import forms
from .models import Train
from cities.models import City


class TrainForm(forms.ModelForm):
    name = forms.CharField(label='Поезд', widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Введите номер поезда'}))

    from_city = forms.ModelChoiceField(label='Откуда', queryset=City.objects.all(), widget=forms.Select(
        attrs={'class': 'form-control',
               'placeholder': 'Откуда'}
    ))

    to_city = forms.ModelChoiceField(label='Куда', queryset=City.objects.all(), widget=forms.Select(
        attrs={'class': 'form-control',
               'placeholder': 'Куда'}
    ))

    travel_time = forms.IntegerField(label='Время в пути',widget=forms.NumberInput(
        attrs={'class': 'form-control',
               'placeholder': 'Время в пути'}
    ))

    class Meta(object):
        model = Train
        fields = ('name', 'from_city', 'to_city', 'travel_time')

travel/apps/trains/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from .forms import TrainForm
from .models import Train
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin



def home(request):
    trains = Train.objects.all()
    paginator = Paginator(trains, 10)
    page = request.GET.get('page')
    trains = paginator.get_page(page)
    return render(request, 'trains/home.html', {'objects_list': trains})


class TrainCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Train
    form_class = TrainForm
    template_name = 'trains/create.html'
    success_url = reverse_lazy('train:home')
    success_message = 'Поезд успешно создан!'


class TrainDetailView(DetailView):
    model = Train
    queryset = model.objects.all()
    context_object_name = 'object'
    template_name = 'trains/detail.html'


class TrainUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Train
    form_class = TrainForm
    template_name = 'trains/update.html'
    success_url = reverse_lazy('train:home')
    success_message = 'Поезд успешно изменен!'


class TrainDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Train
    template_name = 'trains/delete.html'
    success_url = reverse_lazy('train:home')

    def get(self, request, *args, **kwargs):
        messages.success(request, 'Поезд успешно удален!')
        return self.post(request, *args, **kwargs)

travel/apps/trains/templates/trains/create.html
{% extends "base.html" %}
{% block title %}Создание Поезда{% endblock title %}

{% block content %}
    <h1 class="display-4">Создать новый Поезда</h1>
    <div class="row mx-auto">
        <div class="col-md-4">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Сохранить">
            </form>
        </div>
    </div>
{% endblock %}

travel/apps/trains/templates/trains/delete.html
{% extends "base.html" %}
{% block title %}Удаление Поезда{% endblock title %}

{% block content %}
    <h1 class="display-4">Удалить Поезд</h1>
    <div class="row mx-auto">
        <div class="col-md-4">
            <form method="post">{% csrf_token %}
                <p>Удалить: "{{ object }}"?</p>
                <input type="submit" value="Да, удалить">
            </form>
        </div>
    </div>
    {% endblock %}

travel/apps/trains/templates/trains/detail.html
{% extends "base.html" %}
{% block title %}Поезд{% endblock title %}

{% block content %}
    <h1 class="display-4">Поезд</h1>
    <div class="row">
        <div class="col-md-6">
             <table class="table table-striped">
                 <thead>
                <tr>
                    <th> Номер поезда</th>
                    <th> Откуда</th>
                    <th> Куда</th>
                    <th> Время в пути</th>
                    <th> &nbsp;</th>
                    <th> &nbsp;</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <a href='{% url "train:detail" pk=object.pk%}'>
                            {{object.name}}
                        </a>
                    </td>
                    <td>

                            {{object.from_city}}

                    </td>
                    <td>

                            {{object.to_city}}

                    </td>
                    <td>

                            {{object.travel_time}} ч

                    </td>
                    <td>
                        <a href='{% url "train:update" pk=object.pk%}'>
                            <button type="button" class="btn btn-primary btn-sm">
                                Редактировать
                            </button>
                        </a>
                    </td>
                    <td>
                        <a href='{% url "train:delete" pk=object.pk%}'>
                            <button type="button" class="btn btn-danger btn-sm">
                                Удалить
                            </button>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'train:home' %}"><button type="button" class="btn btn-light">Назад к списку</button></a>
        </div>
    </div>
{% endblock %}

travel/apps/trains/templates/trains/home.html
{% extends "base.html" %}
{% block title%}Поезда {% endblock%}

{% block content%}
    <h1 class="display-4 text-center my-4">Поезда</h1>
    <div class="row ">
        <div class='col-md-8 mx-auto'>
            <table class="table table-striped">
                 <thead>
                <tr>
                    <th> Номер поезда</th>
                    <th> Откуда</th>
                    <th> Куда</th>
                    <th> Время в пути</th>
                    <th> &nbsp;</th>
                    <th> &nbsp;</th>
                </tr>
                </thead>
                <tbody>
                {% for object in objects_list%}

                <tr>
                    <td>
                        <a href='{% url "train:detail" pk=object.pk%}'>
                            {{object.name}}
                        </a>
                    </td>
                    <td>

                            {{object.from_city}}

                    </td>
                    <td>

                            {{object.to_city}}

                    </td>
                    <td>

                            {{object.travel_time}} ч

                    </td>
                    <td>
                        <a href='{% url "train:update" pk=object.pk%}'>
                            <button type="button" class="btn btn-primary btn-sm">
                                Редактировать
                            </button>
                        </a>
                    </td>
                    <td>
                        <a href='{% url "train:delete" pk=object.pk%}'>
                            <button type="button" class="btn btn-danger btn-sm">
                                Удалить
                            </button>
                        </a>
                    </td>
                </tr>

                {% endfor %}
                </tbody>
            </table>
        </div>
        <div id="navigation" class="container my-4">
            <div class="row">
                <div class="col-md-3 mx-5">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if objects_list.has_previous %}
                                <li class="page-item">
                                <a class="page-link" href="?page={{ objects_list.previous_page_number }}"
                                        aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>

                                </a>
                                </li>
                            {% else %}

                            {% endif %}
                            {% for page in objects_list.paginator.page_range %}
                                {% if page == objects_list.number %}
                                    <li class="page-item active">
                                        <a class="page-link" href="#"> {{page}}
                                            <span class="sr-only">(current)</span>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link"
                                            href="?page={{page}}">
                                            {{page}}
                                        </a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if objects_list.has_next %}
                                <li class="page-item">
                                <a class="page-link"
                                    href="?page={{ objects_list.paginator.num_pages }}"
                                        aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                                </li>
                            {% else %}
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class='col-md-6'>
             <a href='{% url "train:add" %}'>
                <button type="button" class="btn btn-info btn-sm">
                    Добавить новый Поезд
                </button>
            </a>
        </div>
    </div>
{% endblock%}

travel/apps/trains/templates/trains/update.html
{% extends "base.html" %}
{% block title %}Редактирование Поездов{% endblock title %}

{% block content %}
    <h1 class="display-4">Редактировать Поезд</h1>
    <div class="row mx-auto">
        <div class="col-md-4">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Сохранить">
            </form>
        </div>
    </div>
{% endblock %}